### ISSUE TITLE
User Story: Add user account signup

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#11]
As a **user**, I can **sign up for an account**, so that **I can access functionality reserved for registered users**

**Acceptance Criteria:**
- [x] User can enter a username, email and password and register for an account
- [x] The form tells the user if any of the details they have entered are invalid
- [x] User is given feedback that their account signup was successful

**Tasks:**
- [x] Create signup page view & template
- [x] Create signup form
