### ISSUE TITLE
User Story: Add user login functionality

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#12]
As a **user**, I can **log in to my account**, so that **I can access functionality reserved for registered users**

**Acceptance Criteria:**
- [x] User can log into their account
- [x] User can see that they are logged in while they are using the app

**Tasks:**
- [x] Create login form
- [x] Create visual cues to show the user that they are currently logged in
