### ISSUE TITLE
User Story: Add logout functionality

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#13]
As a **user**, I can **log out of my account**, so that **no one else can access it**

**Acceptance Criteria:**
- [x] User can log out of their account by clicking a link/button
- [x] User is given confirmation that they have logged out successfully

**Tasks:**
- [x] Create logout functionality
- [x] Add 'logout' button somewhere clearly visible on the user interface
- [x] Create confirmation message to display once the user has logged out
