### ISSUE TITLE
User Story: 'Add new event' functionality

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#14]
As a **staff user**, I can **add details of new events**, so that **they are stored in the database**

**Acceptance Criteria:**
- [ ] User can create a new event and enter the following details: date, start time, finish time, venue, name, type, performers
- [ ] User is given confirmation that they have successfully created their event

**Tasks:**
- [ ] Create model for new events
- [ ] Create a form based on this model for the user to enter the details
- [ ] Create views and templates to display this form
- [ ] Create confirmation message to display when an event has been created
