### ISSUE TITLE
User Story:  Create 'Add new venue' functionality

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#15]
As a **staff user**, I can **enter details of a new venue**, so that **they are stored in the database**

**Acceptance Criteria:**
- [x] User can create a new venue and enter the following details: name, location, step-free access y/n, accessible toilets y/n
- [x] User is given confirmation that they have successfully added a venue

**Tasks:**
- [x] Create model for new venues
- [x] Create a form based on this model for the user to enter the details
- [x] Create views and templates to display this form to the user
- [x] Create confirmation message to display when a venue has been added
