### ISSUE TITLE
User Story: Create 'Add performer details' functionality (just Cloudinary photo storage to complete)

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#16]
As a **staff user**, I can **add details of new performers**, so that **they are stored in the database**

**Acceptance Criteria:**
User can create a new performer and enter the following details: 
- [x] name (required), biography (optional), photo (optional), web link (optional)
- [x] User is given confirmation that they have successfully created a new performer record

**Tasks:**
- [x] Create model for new performers including name (required), biography (optional), photo (optional), web link (optional)
- [x] Create a form based on this model for the user to enter the details
- [x] Create views and templates to display this form
- [x] Create confirmation message to display when a new performer record has been created

**Comment by charleymroberts** [comment]
Still to do: enable photo uploads and set up photo storage via Cloudinary (all other tasks now complete)

**Comment by charleymroberts** [comment]
Now complete
