### ISSUE TITLE
User Story: Ability to switch performer records between 'draft' and 'public'

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#24]
As a **staff user**, I can **choose to set a performer record to 'draft' or 'public'**, so that **I can remove a performer from appearing in the public programme without deleting all their information from the database**

**Acceptance Criteria:**
- [ ] User can choose if the performer record is set to 'draft' (so it doesn't appear on the public programme) or 'public'

**Tasks:**
- [ ] Add draft/public option on the user interface
- [ ] Add condition to the code to only display performer records that are set to public

**Comment by charleymroberts** [comment]
This feature will not be added in this iteration of the product. It will be considered for addition as part of a future iteration.
