### ISSUE TITLE
User Story: Display list of all events (published and draft) to staff users

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#25]
As a **staff user**, I can **view a full list of all events added so far**, so that **I can view other organisers' plans and avoid clashes or double bookings**

**Acceptance Criteria:**
- [x] User can view a list of all events that have been added so far

**Tasks:**
- [x] Create view and template for a list of all events
- [x] Create functionality that displays all events within the template
