### ISSUE TITLE
User Story: Create public events programme

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#28]
As a **member of the public**, I can **view a list of all published events**, so that **I can see what will be happening at the festival**

**Acceptance Criteria:**
- [x] Publicly available list of all published events (e.g. on a webpage), without the user needing to log in to view them

**Tasks:**
- [x] Create view and template for public events list
- [x] Enable all events set to 'published' to appear on this list
