### ISSUE TITLE
User Story: Create option for public users to 'favourite' events when logged in

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#30]
As a **public user**, I can **select my favourite events**, so that **I can more easily view events I am particularly interested in attending**

**Acceptance Criteria:**
- [ ] Public users should be able to select favourite events (e.g. by clicking on a heart or star icon) when logged in
- [ ] These events should be gathered in a list, either on a separate page, or with a filter option to only few favourite events

**Tasks:**
- [ ] Add icon to individual events which can be selected by public users
- [ ] Create list functionality (either on a separate page or as a filter option on the main list)

**Comment by charleymroberts** [comment]
This feature will not be added in this iteration of the product. It will be considered for addition as part of a future iteration. This feature should be a high priority for a future iteration.  

Note that the 'login required' (vs 'permissions' needed for staff users) have been left in place for now in the initial version of the product ready for future use.
