### ISSUE TITLE
User Story: Enable users to view additional details about performers

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#31]
As a **public user**, I can **see more information about individual performers in the programme**, so that **I can find out more about what they do**

**Acceptance Criteria:**
- [x] Users can click through from performer names in the programme to view an individual page with more detail (any or all of biography, photo or web link) about that performer

**Tasks:**
- [x] Enable creation of individual pages for each performer using information added by the staff users
- [x] Make names of performers who have extra information in their record appear as a link to this individual page
