### ISSUE TITLE
User Story: Implement mobile-friendly user interface for public events list

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#32]
As a **member of the public**, I can **view the public events programme easily on my phone**, so that **I can use it as a programme when I am out and about at the festival**

**Acceptance Criteria:**
- [x] Interface should display all event details clearly without the user having to scroll sideways on their phone
- [x] Each event should not take up more than half a screen length on most mobile phones (to avoid excessive scrolling top to bottom to read the full list)

**Tasks:**
- [x] Implement mobile-friendly user interface that meets the above criteria
