### ISSUE TITLE
User Story: Implement intuitive user interface for staff users

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#33]
As a **staff user**, I can **easily add or edit information using my laptop/desktop computer or my phone/tablet**, so that **I don't have to waste time learning to use a non-intuitive user interface**

**Acceptance Criteria:**
- [x] Interface should be simple to use without the user having to spend time looking at instructions
- [x] Available actions should be easily visible on the home screen

**Tasks:**
- [x]  Implement simple to use and intuitive user interface following best practices, particularly for laptop/desktop but also for phone/tablet
- [x] Ensure that available actions are visible on the home screen

**Comment by charleymroberts** [comment]
This issue is now complete.
