### ISSUE TITLE
User Story: Ensure main actions for all users are visible on their home screens

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#34]
As a **user**, I can **easily navigate around the app, without using browser back buttons**, so that **I don't get frustrated and give up trying to use it**

**Acceptance Criteria:**
- [x] Navigation to all parts of the app should be simple and intuitive

**Tasks:**
- [x] Ensure all actions are located in obvious places to make them easy for users to find
- [x] Ensure that the browser back buttons are not needed for navigation around the app
