### ISSUE TITLE
User Story: Create 'add new events' functionality

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#35]
As a **staff user**, I can **add new events**, so that **they are stored in the database**

**Acceptance Criteria:**
User can add new events with the following information:
- [x] date
- [x] start time
- [x] end time
- [x] name
- [x] type
- [x] venue
- [x] performers

**Tasks:**
- [x] Enable view and template for 'add events' page
- [x] Create model for events
- [x] Create custom form based on events model
- [x] Connect form with database
