### ISSUE TITLE
User Story: Enable low-IT festivals to use this system

### ISSUE THREAD

**Issue by Ozzard** [charleymroberts/events-manager#36]
As an organiser for a small festival without an in-house techie, I can enrol in a version of this system that I don't have to deploy and manage myself, so that I can manage my festival simply.

**Acceptance Criteria:**
- [ ] Multiple tenants can enrol on one deployed system.
- [ ] Each tenant can provide their own branding and policies, including their own URL (host header) for system access that determines the presented branding.
- [ ] A system manager may manage tenants, and may view and interact with the system as any tenant.
- [ ] Tenants cannot see each other's data.
- [ ] QUESTION: If a punter has an account for one festival, can they use the same account to view another festival if they're also going to that one?

**Tasks:**
- [ ] TODO: Write after the acceptance criteria are sorted.
