### ISSUE TITLE
User Story: Writing the user story template

### ISSUE THREAD

**Issue by charleymroberts** [charleymroberts/events-manager#6]
EPIC: 0

As a **developer**, I can **prioritise my tasks**, so that **I can work more effectively**

**Acceptance criteria**

The developer must be able to:

- [x] Select the template
- [x] Add acceptance criteria
- [x] Tick off acceptance criteria
- [x] Add tasks
- [x] Tick off tasks

**Tasks**

- [x] Write a user story template
- [x] Add checkboxes to the list items

**Comment by charleymroberts** [comment]
This issue is now resolved
